const SampleEvents = [
    {
      id: 1,
      title: "Tech Conference 2024",
      description: "An annual gathering of tech enthusiasts and professionals.",
      location: "San Francisco, CA",
      date: "2024-12-15",
      time: "10:00 AM",
      category: "Technology",
      ticket_price: 150.0,
    },
    {
      id: 2,
      title: "Music Festival",
      description: "A weekend of music, food, and fun with top artists.",
      location: "Austin, TX",
      date: "2024-12-20",
      time: "5:00 PM",
      category: "Entertainment",
      ticket_price: 75.0,
    },
    {
      id: 3,
      title: "Art Exhibition",
      description: "Explore modern art from upcoming and established artists.",
      location: "New York, NY",
      date: "2024-12-10",
      time: "1:00 PM",
      category: "Art",
      ticket_price: 20.0,
    },
    {
      id: 4,
      title: "Startup Pitch Night",
      description: "Watch startups pitch their ideas to investors.",
      location: "Seattle, WA",
      date: "2024-12-12",
      time: "6:30 PM",
      category: "Business",
      ticket_price: 0.0,
    },
    {
      id: 5,
      title: "Charity Run",
      description: "Join us for a 5k run to support local charities.",
      location: "Chicago, IL",
      date: "2024-12-05",
      time: "7:00 AM",
      category: "Community",
      ticket_price: 25.0,
    },
  ];
  
  export default SampleEvents;